### ISSUE TITLE
Symbol Table & code generation

### ISSUE THREAD

**Issue by mmoanis** [mohamed-moanis/c--#6]
We don't know how to do that, all my ideas comes from the calculator tutorial - page 19~.
please read it. Also the symbol table its a pure data structure issue, we need a hash table or whatever in c.

**Comment by mmoanis** [comment]
@MohamedAsaker  we need a table that can hold variables by name, and hold information about the variable most importantly the scope and type.

**Comment by MohamedAsaker** [comment]
we can make  a stack to handle scopes :dancer:

**Comment by mmoanis** [comment]
Why?? we can just add an integer to specify for each symbol its scope level.
When inserting new symbol, and look up it the name was taken compare the scope levels also.

**Comment by mmoanis** [comment]
aslan we need no scopes, except for the functions!!!
